# Generated by Django 4.2.11 on 2024-04-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('bzy', models.JSONField()),
                ('duration', models.CharField(max_length=255)),
                ('photo', models.TextField()),
                ('description', models.TextField()),
                ('ingredients', models.JSONField()),
                ('steps', models.JSONField()),
                ('tag', models.ManyToManyField(blank=True, null=True, related_name='recipes', to='liveRecipes.tag')),
            ],
        ),
    ]
